### PR TITLE
x265: fix for Darwin PPC

### PR DESCRIPTION
**Pull request by barracuda156**
This PR solves the following problems:

1. Adds `ppc` arch, which has been missing.
2. Disables Altivec for Darwin PPC, since its existing in `x265` implementation uses instructions from later ISA, unsupported on Darwin: https://trac.macports.org/ticket/64781
3. `-mcpu=power8` flag should not be used on Darwin.

### CODE REVIEW

**Review by lawchingman — APPROVED** [review]

**Comment by barracuda156** [comment]
Unless someone is gonna fix Altivec implementation for Darwin and ISA 2.02, I guess it is safe to merge :)

**Comment by galad87** [comment]
This is a read-only repository, see https://bitbucket.org/multicoreware/x265_git/wiki/Contribute

**Review by lawchingman — APPROVED** [review]

**Review by lawchingman — APPROVED** [review]

**Review by lawchingman — APPROVED** [review]

**Review by lawchingman — APPROVED** [review]

**Review by lawchingman — APPROVED** [review]

**Review by lawchingman — APPROVED** [review]

**Comment by chouquette** [comment]
Hi,
As mentioned above, this is a read only repository. Approving the PR repeatedly to notify whomever will not cause the code to be merged.

**Comment by barracuda156** [comment]
Well, okay, I will try to open a PR on that exotic platforms.

**Review by lawchingman — APPROVED** [review]

**Review by lawchingman — APPROVED** [review]

**Pull request closed without merging**
